/**
 * @file runner.mjs
 * @purpose Dispatch research task execution based on manifest runner type.
 *          Supports: python, shell (v0.2.0)
 *          Planned:  r, notebook (v0.3.0)
 */

import { execSync, spawnSync } from "child_process";
import * as path from "path";
import * as fs from "fs";

/**
 * Run a research task script.
 * @param {object} opts
 * @param {string} opts.runner   - "python" | "shell" | "r" | "notebook"
 * @param {string} opts.script   - Absolute path to the script file
 * @param {string} opts.cwd      - Working directory for execution
 * @param {object} [opts.env]    - Additional environment variables
 * @returns {{ success: boolean, stdout: string, stderr: string, exitCode: number }}
 */
export function runScript({ runner, script, cwd, env = {} }) {
  const mergedEnv = { ...process.env, ...env };

  switch (runner) {
    case "python": {
      const pythonCmd = getPythonCmd();
      const result = spawnSync(pythonCmd, [script], {
        cwd,
        env: mergedEnv,
        encoding: "utf8",
        stdio: "pipe",
      });
      return {
        success: result.status === 0,
        stdout: result.stdout || "",
        stderr: result.stderr || "",
        exitCode: result.status ?? 1,
      };
    }

    case "shell": {
      const result = spawnSync(script, [], {
        cwd,
        env: mergedEnv,
        encoding: "utf8",
        stdio: "pipe",
        shell: true,
      });
      return {
        success: result.status === 0,
        stdout: result.stdout || "",
        stderr: result.stderr || "",
        exitCode: result.status ?? 1,
      };
    }

    case "r": {
      console.warn("[runner] R execution is planned for v0.3.0. Skipping.");
      return { success: false, stdout: "", stderr: "R runner not yet supported (v0.3.0)", exitCode: 1 };
    }

    case "notebook": {
      console.warn("[runner] Notebook execution is planned for v0.3.0. Skipping.");
      return { success: false, stdout: "", stderr: "Notebook runner not yet supported (v0.3.0)", exitCode: 1 };
    }

    default: {
      return { success: false, stdout: "", stderr: `Unknown runner type: ${runner}`, exitCode: 1 };
    }
  }
}

/**
 * Resolve the Python command available on the current system.
 * Prefers python3, falls back to python.
 */
function getPythonCmd() {
  for (const cmd of ["python3", "python"]) {
    try {
      const result = spawnSync(cmd, ["--version"], { encoding: "utf8" });
      if (result.status === 0) return cmd;
    } catch {
      // try next
    }
  }
  return "python"; // fallback
}

/**
 * Build a consolidated requirements.txt from all task manifests in a directory.
 * @param {string} tasksDir - Directory containing task subdirectories with task.manifest.yaml
 * @returns {string} requirements.txt content
 */
export function buildRequirementsTxt(tasksDir) {
  const packages = new Map(); // name -> version constraint

  if (!fs.existsSync(tasksDir)) return "";

  for (const taskDir of fs.readdirSync(tasksDir)) {
    const manifestPath = path.join(tasksDir, taskDir, "task.manifest.yaml");
    if (!fs.existsSync(manifestPath)) continue;

    const content = fs.readFileSync(manifestPath, "utf8");
    // Simple YAML parsing for packages section
    const lines = content.split("\n");
    let inPackages = false;
    for (const line of lines) {
      if (line.trim() === "packages:") { inPackages = true; continue; }
      if (inPackages && line.startsWith("      ")) {
        const match = line.match(/^\s+([a-zA-Z0-9_-]+):\s*"([^"]+)"/);
        if (match) {
          const [, pkg, ver] = match;
          // Normalize: ~= prefix means compatible release
          const pinned = ver.startsWith("~=") ? ver : `~=${ver.replace(/^[~^>=<]+/, "")}`;
          packages.set(pkg, pinned);
        }
      } else if (inPackages && !line.startsWith("    ")) {
        inPackages = false;
      }
    }
  }

  const lines = ["# Auto-generated by Liem OS research engine", "# Run: pip install -r requirements.txt", ""];
  for (const [pkg, ver] of packages.entries()) {
    lines.push(`${pkg}${ver}`);
  }
  return lines.join("\n");
}
